/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'declan' at '7/26/17 2:08 PM' with Gradle 2.14.1
 *
 * @author declan, @date 7/26/17 2:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
